---
# ==============================================================================
# Confluent Kafka Broker - Role Tasks
# No shell or command modules - pure Ansible built-in modules only
# ==============================================================================

# ------------------------------------------------------------------------------
# Preflight Checks
# ------------------------------------------------------------------------------
- name: "PREFLIGHT | Assert required AAP credential variables are defined"
  ansible.builtin.assert:
    that:
      - confluent_license is defined and confluent_license | length > 0
      - kafka_admin_password is defined and kafka_admin_password | length > 0
      - ldap_bind_password is defined and ldap_bind_password | length > 0
      - ssl_truststore_password is defined and ssl_truststore_password | length > 0
      - ssl_keystore_password is defined and ssl_keystore_password | length > 0
      - ssl_key_password is defined and ssl_key_password | length > 0
      - broker_id_map[inventory_hostname] is defined
    fail_msg: >-
      One or more required AAP credential variables are missing.
      Ensure the 'Confluent Broker Secrets' Custom Credential is attached
      to this Job Template in AAP. Missing vars will be listed above.
  tags: [preflight]
  # NOTE: no_log is intentionally NOT set here - we are only checking
  # that variables ARE defined, not printing their values.

- name: "PREFLIGHT | Resolve broker_id for this host"
  ansible.builtin.set_fact:
    broker_id: "{{ broker_id_map[inventory_hostname] }}"
  tags: [preflight]

- name: "PREFLIGHT | Display broker identity (no secrets)"
  ansible.builtin.debug:
    msg:
      - "Broker ID    : {{ broker_id }}"
      - "Hostname     : {{ inventory_hostname }}"
      - "Broker Rack  : {{ broker_rack }}"
      - "JMX Port     : {{ kafka_jmx_port }}"
      - "Prom Port    : {{ jmx_exporter_port }}"
  tags: [preflight]

# ------------------------------------------------------------------------------
# System Preparation
# ------------------------------------------------------------------------------
- name: "SYSTEM | Create kafka group"
  ansible.builtin.group:
    name: "{{ kafka_group }}"
    state: present
    system: true
  tags: [system]

- name: "SYSTEM | Create kafka user"
  ansible.builtin.user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    shell: /sbin/nologin
    home: "{{ kafka_home }}"
    create_home: false
    system: true
  tags: [system]

- name: "SYSTEM | Create required directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ kafka_log_dir }}",    mode: "0750" }
    - { path: "{{ kafka_config_dir }}", mode: "0750" }
    - { path: "{{ ssl_dir }}",          mode: "0750" }
    - { path: "{{ secrets_dir }}",      mode: "0700" }   # secrets dir: owner-only
    - { path: "{{ jmx_exporter_dir }}", mode: "0750" }
    - { path: "/var/log/kafka",         mode: "0750" }
  tags: [system]

# ------------------------------------------------------------------------------
# Deploy local-secrets.properties
# This is the file that Confluent SecurePass reads at broker JVM startup.
# It contains the actual plaintext secrets - sourced from AAP credentials.
# It is NEVER committed to Git. It lives only on the broker filesystem.
# ------------------------------------------------------------------------------
- name: "SECRETS | Deploy local-secrets.properties from AAP credential variables"
  ansible.builtin.template:
    src: local-secrets.properties.j2
    dest: "{{ secrets_dir }}/local-secrets.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0600"        # Owner (kafka user) read/write only - no group, no other
    backup: false       # Never keep plaintext backups of secrets files
  no_log: true          # Suppress task output so secrets are never logged in AAP
  notify: restart confluent-kafka
  tags: [secrets, config]

# ------------------------------------------------------------------------------
# JMX Prometheus Exporter
# ------------------------------------------------------------------------------
- name: "JMX | Copy JMX Prometheus exporter JAR to broker"
  ansible.builtin.copy:
    src: "{{ jmx_exporter_jar }}"
    dest: "{{ jmx_exporter_jar_path }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0644"
  notify: restart confluent-kafka
  tags: [jmx, prometheus]

- name: "JMX | Deploy Prometheus JMX exporter metrics config"
  ansible.builtin.template:
    src: kafka-broker-metrics.yml.j2
    dest: "{{ jmx_exporter_config }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0644"
  notify: restart confluent-kafka
  tags: [jmx, prometheus]

# ------------------------------------------------------------------------------
# Broker Configuration
# server.properties contains only SecurePass placeholder references - no secrets
# ------------------------------------------------------------------------------
- name: "CONFIG | Deploy server.properties (SecurePass placeholders only - no secrets)"
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ kafka_config_dir }}/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0640"
    backup: true
  notify: restart confluent-kafka
  tags: [config]

# ------------------------------------------------------------------------------
# Systemd Service
# ------------------------------------------------------------------------------
- name: "SERVICE | Deploy systemd unit file for confluent-kafka"
  ansible.builtin.template:
    src: confluent-kafka.service.j2
    dest: "/etc/systemd/system/{{ kafka_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart confluent-kafka
  tags: [service]

- name: "SERVICE | Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true
  tags: [service]

- name: "SERVICE | Enable and start confluent-kafka service"
  ansible.builtin.systemd:
    name: "{{ kafka_service_name }}"
    enabled: true
    state: started
  tags: [service]

# ------------------------------------------------------------------------------
# Verify Broker Health
# ------------------------------------------------------------------------------
- name: "VERIFY | Wait for broker SASL_SSL port {{ kafka_sasl_ssl_port }}"
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafka_sasl_ssl_port }}"
    timeout: "{{ broker_restart_timeout }}"
    state: started
  tags: [verify]

- name: "VERIFY | Wait for MDS HTTPS port {{ kafka_mds_port }}"
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafka_mds_port }}"
    timeout: "{{ broker_restart_timeout }}"
    state: started
  tags: [verify]

- name: "VERIFY | Wait for Prometheus JMX port {{ jmx_exporter_port }}"
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ jmx_exporter_port }}"
    timeout: "{{ broker_restart_timeout }}"
    state: started
  tags: [verify]

- name: "VERIFY | Gather confluent-kafka service status"
  ansible.builtin.systemd:
    name: "{{ kafka_service_name }}"
  register: kafka_service_status
  tags: [verify]

- name: "VERIFY | Assert broker service is running"
  ansible.builtin.assert:
    that:
      - kafka_service_status.status.ActiveState == "active"
      - kafka_service_status.status.SubState == "running"
    fail_msg: >-
      Broker {{ kafka_service_name }} on {{ inventory_hostname }} is not running.
      ActiveState={{ kafka_service_status.status.ActiveState }}
      SubState={{ kafka_service_status.status.SubState }}
    success_msg: "Broker {{ inventory_hostname }} (ID: {{ broker_id }}) is healthy."
  tags: [verify]
