---
# ==============================================================================
# Confluent Kafka Broker - Handlers
# ==============================================================================

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: restart confluent-kafka
  ansible.builtin.systemd:
    name: "{{ kafka_service_name }}"
    state: restarted
  listen: restart confluent-kafka
