---
# ==============================================================================
# Create required broker directories
# Mirrors: roles/zookeeper/tasks/create_directories.yml
# ==============================================================================

- name: Create broker data directory
  ansible.builtin.file:
    path: "{{ broker_data_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0755"
    recurse: true

- name: Create broker log directory
  ansible.builtin.file:
    path: "{{ broker_log_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0755"
    recurse: true

- name: Create broker config directory
  ansible.builtin.file:
    path: "{{ broker_config_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0755"

- name: Create SSL directory
  ansible.builtin.file:
    path: "{{ ssl_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0750"

- name: Create secrets directory (owner-only access)
  ansible.builtin.file:
    path: "{{ broker_secrets_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0700"

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0755"
  loop:
    - /opt/prometheus
    - /opt/prometheus/prometheus-config
