---
# ==============================================================================
# Create user, group, and required directories
# ==============================================================================

- name: "DIRS | Create confluent group"
  ansible.builtin.group:
    name: "{{ c3_group }}"
    state: present

- name: "DIRS | Create confluent user"
  ansible.builtin.user:
    name: "{{ c3_user }}"
    group: "{{ c3_group }}"
    shell: /bin/bash
    create_home: true
    state: present

- name: "DIRS | Create required directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ c3_user }}"
    group: "{{ c3_group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ c3_data_dir }}",           mode: "0755" }
    - { path: "{{ c3_data_tmp_dir }}",       mode: "0755" }
    - { path: "{{ c3_log_dir }}",            mode: "0755" }
    - { path: "{{ c3_ssl_dir }}",            mode: "0755" }
    - { path: "{{ c3_secrets_dir }}",        mode: "0700" }
    - { path: "{{ c3_scripts_dir }}",        mode: "0755" }
    - { path: "{{ c3_install_dir }}",        mode: "0755" }
    - { path: /opt/logarchive,               mode: "0755" }
    - { path: /etc/confluent-control-center, mode: "0755" }
