---
# ==============================================================================
# Deploy local-secrets.properties
#
# This file is read by Confluent SecurePass config provider at broker JVM
# startup. It resolves all ${securepass:...} placeholders in server.properties.
#
# Source  : templates/local-secrets.properties.j2
# Dest    : {{ broker_secrets_dir }}/local-secrets.properties
# Owner   : {{ broker_user }}  Mode: 0600 (owner read/write only)
#
# Values come from AAP Custom Credential injected as extra_vars.
# This file is NEVER committed to Git.
# ==============================================================================

- name: "SECRETS | Assert all AAP credential variables are present"
  ansible.builtin.assert:
    that:
      - confluent_license is defined and confluent_license | length > 0
      - kafka_admin_password is defined and kafka_admin_password | length > 0
      - ldap_bind_password is defined and ldap_bind_password | length > 0
      - ssl_truststore_password is defined and ssl_truststore_password | length > 0
      - ssl_keystore_password is defined and ssl_keystore_password | length > 0
      - ssl_key_password is defined and ssl_key_password | length > 0
    fail_msg: >-
      One or more AAP credential variables are missing.
      Attach the 'Confluent Broker Secrets' Custom Credential to this Job Template.
  # no_log intentionally omitted - we are only asserting existence, not printing values

- name: "SECRETS | Deploy local-secrets.properties from AAP credential variables"
  ansible.builtin.template:
    src: local-secrets.properties.j2
    dest: "{{ broker_secrets_dir }}/local-secrets.properties"
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0600"      # kafka user read/write only - no group, no other
    backup: false     # never keep plaintext backups of secrets files
  no_log: true        # suppress task output - secrets must never appear in AAP logs
  notify: restart confluent-kafka
