---
# ==============================================================================
# Confluent Kafka Broker Deployment Playbook
# Hosts  : broker_nodes group (defined in AAP inventory)
# Secrets: group_vars/secret.yml  (Ansible Vault, password: humana#1)
#
# AAP Job Template requires TWO credentials:
#   1. Machine credential  - SSH access to brokers
#   2. Vault credential    - password humana#1  to decrypt group_vars/secret.yml
#
# What this playbook does (serial: 1 = rolling, one broker at a time):
#   create_user → create_directories → install_confluent → setup_prometheus
#   → deploy_secrets (writes /opt/secrets/local-secrets.properties)
#   → configure → configure_service → start_service → validate
# ==============================================================================

- name: Deploy Confluent Kafka Broker Cluster
  hosts: broker_nodes
  become: true
  gather_facts: true
  serial: 1

  vars_files:
    - "{{ playbook_dir }}/../group_vars/secret.yml"

  roles:
    - broker

  post_tasks:
    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          ============================================
          Kafka Broker Deployment Complete
          ============================================
          Nodes:
          {% for host in groups['broker_nodes'] %}
          - {{ hostvars[host]['ansible_fqdn'] }} (ID: {{ hostvars[host]['broker_id'] }})
          {% endfor %}

          Configuration:
          - Install Dir  : {{ broker_install_dir }}
          - Data Dir     : {{ broker_data_dir }}
          - Config Dir   : {{ broker_config_dir }}
          - Secrets File : {{ broker_secrets_dir }}/local-secrets.properties
          - SASL_SSL Port: {{ kafka_sasl_ssl_port }}
          - TOKEN Port   : {{ kafka_token_port }}
          - AD Port      : {{ kafka_ad_port }}
          - MDS Port     : {{ kafka_mds_port }}
          - Prometheus   : {{ prometheus_jmx_exporter_port }}
          ============================================
      run_once: true
