---
# ==============================================================================
# deploy_secrets.yml
#
# PURPOSE:
#   Write /opt/secrets/local-secrets.properties from Ansible Vault variables.
#   Also exports CONFLUENT_SECURITY_MASTER_KEY to /etc/profile.d/master_key.sh.
#
# HOW VARIABLES ARE LOADED (in priority order):
#   1. vars_files: in the playbook loads group_vars/all.yml + vault_secrets.yml
#   2. This task re-loads vault_secrets.yml via include_vars as a safety net
#      in case the task is called standalone or group_vars did not load.
#
# VAULT FILE:
#   group_vars/vault_secrets.yml  (AES256)
#   Variables: vault_kafka_admin_password,
#              vault_ldap_bind_password, vault_ssl_truststore_password,
#              vault_ssl_keystore_password, vault_ssl_key_password,
#              vault_confluent_security_master_key,
#              vault_jfrog_user, vault_jfrog_password,
#              vault_oidc_client_secret
#
# OUTPUT:
#   /opt/secrets/local-secrets.properties  (mode 0600, confluent:confluent)
#   Read by Confluent SecurePass at JVM startup only.
# ==============================================================================

# ------------------------------------------------------------------
# Step 1: Re-load vault_secrets.yml explicitly inside the role.
# ------------------------------------------------------------------
- name: "SECRETS | Load vault_secrets.yml"
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/vault_secrets.yml"
  no_log: true

# ------------------------------------------------------------------
# Step 2: Assert all vault variables are decrypted and non-empty.
# ------------------------------------------------------------------
- name: "SECRETS | Assert all vault_ variables are defined and non-empty"
  ansible.builtin.assert:
    that:
      - vault_kafka_admin_password          is defined and vault_kafka_admin_password          | length > 0
      - vault_ldap_bind_password            is defined and vault_ldap_bind_password            | length > 0
      - vault_ssl_truststore_password       is defined and vault_ssl_truststore_password       | length > 0
      - vault_ssl_keystore_password         is defined and vault_ssl_keystore_password         | length > 0
      - vault_ssl_key_password              is defined and vault_ssl_key_password              | length > 0
      - vault_confluent_security_master_key is defined and vault_confluent_security_master_key | length > 0
      - vault_jfrog_user                    is defined and vault_jfrog_user                    | length > 0
      - vault_jfrog_password                is defined and vault_jfrog_password                | length > 0
      - vault_oidc_client_secret            is defined and vault_oidc_client_secret            | length > 0
    fail_msg: |
      vault_ variables are missing or empty. Check:
        1. group_vars/vault_secrets.yml exists in the Git project
        2. AAP Vault credential is attached to this Job Template
           Resources -> Templates -> Edit -> Credentials -> add Vault credential
    success_msg: "All vault_ variables loaded from vault_secrets.yml"
  no_log: true

# ------------------------------------------------------------------
# Step 3: Map vault_ variables to plain names used by templates.
# ------------------------------------------------------------------
- name: "SECRETS | Map vault_ variables to plain names"
  ansible.builtin.set_fact:
    kafka_admin_password:          "{{ vault_kafka_admin_password }}"
    ldap_bind_password:            "{{ vault_ldap_bind_password }}"
    ssl_truststore_password:       "{{ vault_ssl_truststore_password }}"
    ssl_keystore_password:         "{{ vault_ssl_keystore_password }}"
    ssl_key_password:              "{{ vault_ssl_key_password }}"
    confluent_security_master_key: "{{ vault_confluent_security_master_key }}"
    jfrog_user:                    "{{ vault_jfrog_user }}"
    jfrog_password:                "{{ vault_jfrog_password }}"
    oidc_client_secret:            "{{ vault_oidc_client_secret }}"
  no_log: true

# ------------------------------------------------------------------
# Step 4: Ensure /opt/secrets exists with correct permissions.
# ------------------------------------------------------------------
- name: "SECRETS | Ensure {{ broker_secrets_dir }} exists (mode 0700)"
  ansible.builtin.file:
    path: "{{ broker_secrets_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0700"

# ------------------------------------------------------------------
# Step 5: Render vault variables -> local-secrets.properties
# ------------------------------------------------------------------
- name: "SECRETS | Write {{ broker_secrets_dir }}/local-secrets.properties"
  ansible.builtin.template:
    src: local-secrets.properties.j2
    dest: "{{ broker_secrets_dir }}/local-secrets.properties"
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0600"
    backup: false
  no_log: true
  notify: restart confluent-kafka

# ------------------------------------------------------------------
# Step 6: Export CONFLUENT_SECURITY_MASTER_KEY to profile.d
# ------------------------------------------------------------------
- name: "SECRETS | Write CONFLUENT_SECURITY_MASTER_KEY to /etc/profile.d/master_key.sh"
  ansible.builtin.lineinfile:
    path: /etc/profile.d/master_key.sh
    line: "export CONFLUENT_SECURITY_MASTER_KEY='{{ vault_confluent_security_master_key }}'"
    regexp: "^export CONFLUENT_SECURITY_MASTER_KEY="
    create: true
    mode: '0644'
  no_log: true

# ------------------------------------------------------------------
# Step 7: Confirm file was created with correct owner and mode.
# ------------------------------------------------------------------
- name: "SECRETS | Stat {{ broker_secrets_dir }}/local-secrets.properties"
  ansible.builtin.stat:
    path: "{{ broker_secrets_dir }}/local-secrets.properties"
  register: secrets_stat

- name: "SECRETS | Assert local-secrets.properties exists with mode 0600"
  ansible.builtin.assert:
    that:
      - secrets_stat.stat.exists
      - secrets_stat.stat.mode == "0600"
      - secrets_stat.stat.pw_name == broker_user
    fail_msg: |
      FAILED: {{ broker_secrets_dir }}/local-secrets.properties not created correctly.
        exists = {{ secrets_stat.stat.exists }}
        mode   = {{ secrets_stat.stat.mode   | default('unknown') }}
        owner  = {{ secrets_stat.stat.pw_name | default('unknown') }}
    success_msg: >-
      OK: local-secrets.properties written
      (mode={{ secrets_stat.stat.mode }}, owner={{ secrets_stat.stat.pw_name }})
