---
# ==============================================================================
# deploy_secrets.yml
#
# PURPOSE:
#   1. Include group_vars/secret.yml (vault-encrypted) to load vault_ variables
#   2. Assert all 6 vault_ secrets are decrypted and non-empty
#   3. Render local-secrets.properties.j2 → /opt/secrets/local-secrets.properties
#   4. Verify file exists on disk with correct owner and mode 0600
#
# VAULT:
#   File     : group_vars/secret.yml
#   Password : humana#1  (stored in AAP as built-in 'Vault' credential)
#   Variables: vault_confluent_license, vault_kafka_admin_password,
#              vault_ldap_bind_password, vault_ssl_truststore_password,
#              vault_ssl_keystore_password, vault_ssl_key_password
#
# OUTPUT:
#   /opt/secrets/local-secrets.properties  (mode 0600, owner kafka:kafka)
#   Read by Confluent SecurePass at JVM startup to resolve ${securepass:...}
#   placeholders in server.properties.  Never written back to any file.
# ==============================================================================

# ------------------------------------------------------------------
# Step 1: Explicitly include the vault secrets file
# include_vars decrypts using the AAP Vault credential at runtime.
# Path is relative to the playbook root (project root in AAP).
# ------------------------------------------------------------------
- name: "SECRETS | Load group_vars/secret.yml from vault"
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/secret.yml"
  no_log: true

# ------------------------------------------------------------------
# Step 2: Assert all vault_ variables are defined and not empty.
# If any are missing the vault file is wrong or vault credential
# is not attached to the Job Template.
# ------------------------------------------------------------------
- name: "SECRETS | Assert all vault variables are defined and non-empty"
  ansible.builtin.assert:
    that:
      - vault_confluent_license       is defined and vault_confluent_license       | length > 0
      - vault_kafka_admin_password    is defined and vault_kafka_admin_password    | length > 0
      - vault_ldap_bind_password      is defined and vault_ldap_bind_password      | length > 0
      - vault_ssl_truststore_password is defined and vault_ssl_truststore_password | length > 0
      - vault_ssl_keystore_password   is defined and vault_ssl_keystore_password   | length > 0
      - vault_ssl_key_password        is defined and vault_ssl_key_password        | length > 0
    fail_msg: >-
      One or more vault_ variables are missing or empty.
      Check that:
        1. group_vars/secret.yml exists in the project
        2. The AAP Vault credential (password: humana#1) is attached to this Job Template
        3. The vault_ variable names in secret.yml match exactly
    success_msg: "All vault variables loaded successfully from secret.yml"
  no_log: true

# ------------------------------------------------------------------
# Step 3: Ensure /opt/secrets directory exists with correct perms
# (also done in create_directories.yml but idempotent to repeat)
# ------------------------------------------------------------------
- name: "SECRETS | Ensure {{ broker_secrets_dir }} directory exists"
  ansible.builtin.file:
    path: "{{ broker_secrets_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0700"

# ------------------------------------------------------------------
# Step 4: Render local-secrets.properties from the Jinja2 template.
# no_log: true prevents the rendered plaintext secrets from appearing
# in AAP job output logs.
# ------------------------------------------------------------------
- name: "SECRETS | Write /opt/secrets/local-secrets.properties from vault"
  ansible.builtin.template:
    src: local-secrets.properties.j2
    dest: "{{ broker_secrets_dir }}/local-secrets.properties"
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0600"
    backup: false
  no_log: true
  notify: restart confluent-kafka

# ------------------------------------------------------------------
# Step 5: Verify the file was written with correct permissions.
# stat is safe - it does not read or expose file contents.
# ------------------------------------------------------------------
- name: "SECRETS | Stat local-secrets.properties"
  ansible.builtin.stat:
    path: "{{ broker_secrets_dir }}/local-secrets.properties"
  register: secrets_stat

- name: "SECRETS | Assert local-secrets.properties exists with mode 0600"
  ansible.builtin.assert:
    that:
      - secrets_stat.stat.exists
      - secrets_stat.stat.mode == "0600"
      - secrets_stat.stat.pw_name == broker_user
    fail_msg: >-
      FAILED: {{ broker_secrets_dir }}/local-secrets.properties
      was not created or has wrong permissions.
      exists={{ secrets_stat.stat.exists }}
      mode={{ secrets_stat.stat.mode | default('unknown') }}
      owner={{ secrets_stat.stat.pw_name | default('unknown') }}
    success_msg: >-
      OK: {{ broker_secrets_dir }}/local-secrets.properties
      created (mode=0600, owner={{ secrets_stat.stat.pw_name }})
