---
# ==============================================================================
# Extract and install Confluent from local tar file
# Mirrors: roles/zookeeper/tasks/install_confluent.yml
# ==============================================================================

- name: Check if Confluent package exists on remote host
  ansible.builtin.stat:
    path: "{{ confluent_package_path }}"
  register: confluent_tar

- name: Fail if Confluent package not found
  ansible.builtin.fail:
    msg: >-
      Confluent package not found at {{ confluent_package_path }} on {{ inventory_hostname }}.
      Please copy {{ confluent_package_path }} to the host before running this playbook.
  when: not confluent_tar.stat.exists

- name: Create install directory
  ansible.builtin.file:
    path: "{{ broker_install_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    mode: "0755"

- name: Extract Confluent package to /tmp
  ansible.builtin.unarchive:
    src: "{{ confluent_package_path }}"
    dest: /tmp/
    remote_src: true
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
  register: extract_result

- name: Find extracted Confluent directory
  ansible.builtin.find:
    paths: /tmp
    patterns: "confluent*"
    file_type: directory
  register: confluent_dirs

- name: Set extracted directory fact
  ansible.builtin.set_fact:
    extracted_dir: "{{ confluent_dirs.files | sort(attribute='path') | last | attr('path') }}"
  when: confluent_dirs.matched > 0

- name: Fail if extraction produced no directory
  ansible.builtin.fail:
    msg: "No confluent* directory found in /tmp after extraction. Check tar contents."
  when: confluent_dirs.matched == 0

- name: Synchronize extracted Confluent to install directory
  ansible.posix.synchronize:
    src: "{{ extracted_dir }}/"
    dest: "{{ broker_install_dir }}/"
    archive: true
    delete: false
  delegate_to: "{{ inventory_hostname }}"

- name: Set ownership on install directory
  ansible.builtin.file:
    path: "{{ broker_install_dir }}"
    state: directory
    owner: "{{ broker_user }}"
    group: "{{ broker_group }}"
    recurse: true

- name: Verify Kafka broker binary exists
  ansible.builtin.stat:
    path: "{{ broker_install_dir }}/bin/kafka-server-start"
  register: kafka_binary

- name: Fail if Kafka binary not found
  ansible.builtin.fail:
    msg: >-
      kafka-server-start binary not found in {{ broker_install_dir }}/bin.
      Verify the tar contains a valid Confluent Platform distribution.
  when: not kafka_binary.stat.exists
