---
# Default variables - lowest precedence, override via group_vars or AAP extra vars

install_java: false
create_broker_user: true
configure_firewall: false
start_broker: true
enable_broker: true
validate_deployment: true
prometheus_jmx_exporter_enabled: true

---
# Handlers

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart confluent-kafka
  ansible.builtin.systemd:
    name: "{{ broker_service_name }}"
    state: restarted

---
# ==============================================================================
# Main tasks - Confluent Kafka Broker deployment
# Mirrors: roles/zookeeper/tasks/main.yml pattern
# ==============================================================================

- name: Display deployment info
  ansible.builtin.debug:
    msg: "Deploying Confluent Kafka Broker on {{ ansible_fqdn }}"

- name: Create user and group
  ansible.builtin.include_tasks: create_user.yml
  when: create_broker_user | bool

- name: Create directories
  ansible.builtin.include_tasks: create_directories.yml

- name: Extract and install Confluent
  ansible.builtin.include_tasks: install_confluent.yml

- name: Setup Prometheus JMX Exporter
  ansible.builtin.include_tasks: setup_prometheus.yml
  when: prometheus_jmx_exporter_enabled | bool

- name: Deploy local-secrets.properties from AAP credentials
  ansible.builtin.include_tasks: deploy_secrets.yml

- name: Configure Kafka Broker
  ansible.builtin.include_tasks: configure.yml

- name: Configure systemd service
  ansible.builtin.include_tasks: configure_service.yml

- name: Start Kafka Broker service
  ansible.builtin.include_tasks: start_service.yml
  when: start_broker | bool

- name: Validate deployment
  ansible.builtin.include_tasks: validate.yml
  when: validate_deployment | bool


