---
# ==============================================================================
# Start Kafka Broker service
# Mirrors: roles/zookeeper/tasks/start_service.yml
# ==============================================================================

- name: Enable confluent-kafka service
  ansible.builtin.systemd:
    name: "{{ broker_service_name }}"
    enabled: true

- name: Start confluent-kafka service
  ansible.builtin.systemd:
    name: "{{ broker_service_name }}"
    state: started

- name: Wait for broker SASL_SSL port {{ kafka_sasl_ssl_port }} to open
  ansible.builtin.wait_for:
    port: "{{ kafka_sasl_ssl_port }}"
    delay: 10
    timeout: "{{ broker_restart_timeout }}"

- name: Wait for MDS port {{ kafka_mds_port }} to open
  ansible.builtin.wait_for:
    port: "{{ kafka_mds_port }}"
    delay: 5
    timeout: "{{ broker_restart_timeout }}"

- name: Wait for Prometheus JMX port {{ prometheus_jmx_exporter_port }} to open
  ansible.builtin.wait_for:
    port: "{{ prometheus_jmx_exporter_port }}"
    delay: 5
    timeout: "{{ broker_restart_timeout }}"
  when: prometheus_jmx_exporter_enabled | bool
