---
# ==============================================================================
# Validate Kafka Broker deployment
# Mirrors: roles/zookeeper/tasks/validate.yml
# ==============================================================================

- name: Check confluent-kafka service status
  ansible.builtin.systemd:
    name: "{{ broker_service_name }}"
  register: broker_status

- name: Verify broker service is running
  ansible.builtin.assert:
    that:
      - broker_status.status.ActiveState == "active"
      - broker_status.status.SubState == "running"
    fail_msg: >-
      Kafka broker service is not running on {{ inventory_hostname }}.
      ActiveState={{ broker_status.status.ActiveState }}
      SubState={{ broker_status.status.SubState }}
    success_msg: "Kafka broker service is active and running."

- name: Verify SASL_SSL port {{ kafka_sasl_ssl_port }} is listening
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafka_sasl_ssl_port }}"
    timeout: 30
    state: started

- name: Verify TOKEN port {{ kafka_token_port }} is listening
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafka_token_port }}"
    timeout: 30
    state: started

- name: Verify AD port {{ kafka_ad_port }} is listening
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafka_ad_port }}"
    timeout: 30
    state: started

- name: Verify MDS port {{ kafka_mds_port }} is listening
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ kafka_mds_port }}"
    timeout: 30
    state: started

- name: Check Prometheus metrics endpoint
  ansible.builtin.uri:
    url: "http://{{ inventory_hostname }}:{{ prometheus_jmx_exporter_port }}/metrics"
    return_content: false
    status_code: 200
  register: prometheus_check
  failed_when: false
  when: prometheus_jmx_exporter_enabled | bool

- name: Display Prometheus metrics status
  ansible.builtin.debug:
    msg: "Prometheus metrics: {{ 'AVAILABLE' if prometheus_check.status == 200 else 'NOT AVAILABLE' }}"
  when: prometheus_jmx_exporter_enabled | bool

- name: Display broker validation summary
  ansible.builtin.debug:
    msg: |
      Node     : {{ ansible_fqdn }}
      Broker ID: {{ broker_id }}
      Service  : {{ broker_status.status.ActiveState }} / {{ broker_status.status.SubState }}
      PID      : {{ broker_status.status.MainPID }}
      SASL_SSL : {{ kafka_sasl_ssl_port }} OPEN
      TOKEN    : {{ kafka_token_port }} OPEN
      AD       : {{ kafka_ad_port }} OPEN
      MDS      : {{ kafka_mds_port }} OPEN
      Prometheus: {{ prometheus_jmx_exporter_port }} {{ 'OPEN' if prometheus_check.status == 200 else 'CHECK LOGS' }}
